# Generated by Django 5.2 on 2025-05-11 12:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Username must start with a lowercase letter and contain only letters and numbers.', regex='^[a-z][a-zA-Z0-9]*$')]),
        ),
    ]
